repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        name: terraform docs for the root module
        args: ["markdown", "table", "--output-file", "README.md", "./"]
      - id: terraform-docs-go
        name: terraform docs for the 'instance' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/instance"]
      - id: terraform-docs-go
        name: terraform docs for the 'scanning-delegate-role' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/scanning-delegate-role"]
      - id: terraform-docs-go
        name: terraform docs for the 'agentless-scanner-role' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/agentless-scanner-role"]
      - id: terraform-docs-go
        name: terraform docs for the 'user_data' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/user_data"]
      - id: terraform-docs-go
        name: terraform docs for the 'vpc' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/vpc"]
      - id: terraform-docs-go
        name: terraform docs for the 'azure/custom-data' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/azure/custom-data"]
      - id: terraform-docs-go
        name: terraform docs for the 'azure/managed-identity' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/azure/managed-identity"]
      - id: terraform-docs-go
        name: terraform docs for the 'azure/resource-group' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/azure/resource-group"]
      - id: terraform-docs-go
        name: terraform docs for the 'azure/virtual-machine' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/azure/virtual-machine"]
      - id: terraform-docs-go
        name: terraform docs for the 'azure/virtual-network' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/azure/virtual-network"]
  
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.83.6"
    hooks:
      - id: terraform_fmt
        name: terraform fmt
        args: [--args=-recursive]
      - id: terraform_tflint
        name: terraform lint
        args: [--args=--disable-rule=terraform_module_pinned_source]
